# Generated by Django 5.1.4 on 2025-01-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(default="admin", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
