# Generated by Django 5.1.4 on 2025-01-23 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_profile_image_remove_profile_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="is_staff",
        ),
    ]
