# Generated by Django 5.1.4 on 2025-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_profile_is_active_remove_profile_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
