# Generated by Django 5.1.4 on 2025-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_profile_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_staff",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
