# Generated by Django 5.1.4 on 2025-02-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_profile_first_name_alter_profile_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cash_position",
            field=models.FloatField(default=0),
        ),
    ]
