# Generated by Django 5.1.4 on 2025-02-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="quantitity",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="security_type",
            field=models.CharField(
                choices=[
                    ("Stocks", "stocks"),
                    ("MF", "mf"),
                    ("Bond", "bond"),
                    ("ETF", "etf"),
                ],
                default="Stocks",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="ticker",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
