# Generated by Django 5.1.4 on 2025-02-09 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_transactions_ticker_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="quantitity",
            new_name="quantity",
        ),
    ]
