# Generated by Django 5.1.4 on 2024-12-28 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("ticker", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=200, null=True)),
                ("description", models.CharField(max_length=2000)),
                ("country", models.CharField(max_length=100)),
                ("website", models.URLField(null=True)),
                ("address", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ticker", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("cl", models.FloatField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="stocks.company",
                    ),
                ),
            ],
        ),
    ]
