# Generated by Django 5.1.4 on 2024-12-28 14:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="cl",
        ),
    ]
