# Generated by Django 5.1.4 on 2025-12-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_remove_price_cl"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="soctor",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="dividends",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="stock_splits",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="volume",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(
                fields=("ticker", "date"), name="unique_ticker_date"
            ),
        ),
    ]
