# Generated by Django 5.1.4 on 2025-12-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_company_soctor_price_dividends_price_stock_splits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company",
                to="stocks.company",
            ),
        ),
    ]
