# Generated by Django 5.1.4 on 2025-12-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_price_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="volume",
            field=models.BigIntegerField(),
        ),
    ]
