# Generated by Django 5.1.4 on 2026-05-21 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_alter_company_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechnicalIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("date", models.DateField(db_index=True)),
                (
                    "atr_14",
                    models.FloatField(
                        blank=True, help_text="Average True Range (14-day)", null=True
                    ),
                ),
                (
                    "hist_volatility_20",
                    models.FloatField(
                        blank=True,
                        help_text="Annualized 20-day historical volatility",
                        null=True,
                    ),
                ),
                (
                    "rs_industry",
                    models.FloatField(
                        blank=True,
                        help_text="Industry Relative Strength: percentile rank (0-100) of 63-day return within the same industry group",
                        null=True,
                    ),
                ),
                (
                    "vwap_20",
                    models.FloatField(
                        blank=True,
                        help_text="20-day rolling Volume Weighted Average Price",
                        null=True,
                    ),
                ),
                (
                    "beta_252",
                    models.FloatField(
                        blank=True,
                        help_text="252-day rolling beta vs benchmark",
                        null=True,
                    ),
                ),
                (
                    "alpha_252",
                    models.FloatField(
                        blank=True,
                        help_text="252-day rolling annualized alpha vs benchmark",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ticker", "-date"], name="stocks_tech_ticker_34c175_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ticker", "date"), name="unique_technical_ticker_date"
                    )
                ],
            },
        ),
    ]
