  # Generated by Django 5.1.4 on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_technical_indicators"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalindicators",
            name="dma_20",
            field=models.FloatField(
                blank=True,
                help_text="20-day simple moving average of close",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="technicalindicators",
            name="dma_50",
            field=models.FloatField(
                blank=True,
                help_text="50-day simple moving average of close",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="technicalindicators",
            name="dma_200",
            field=models.FloatField(
                blank=True,
                help_text="200-day simple moving average of close",
                null=True,
            ),
        ),
    ]
