# Generated by Django 5.1.4 on 2026-08-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0009_company_industry_subgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="ticker",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="price",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="ticker",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["industry", "country"], name="stocks_comp_industr_90cca9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["ticker", "-date"], name="stocks_pric_ticker_395343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["date", "ticker"], name="stocks_pric_date_ca47de_idx"
            ),
        ),
    ]
